// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/Bhinneka/user-service/src/health/query"
	"github.com/stretchr/testify/mock"
)

// HealthQuery is an autogenerated mock type for the HealthQuery type
type HealthQuery struct {
	mock.Mock
}

// Ping provides a mock function with given fields: message
func (_m *HealthQuery) Ping(message string) <-chan query.ResultQuery {
	ret := _m.Called(message)

	var r0 <-chan query.ResultQuery
	if rf, ok := ret.Get(0).(func(string) <-chan query.ResultQuery); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan query.ResultQuery)
		}
	}

	return r0
}
