// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Bhinneka/user-service/src/service/model"
	mock "github.com/stretchr/testify/mock"
)

// UploadServices is an autogenerated mock type for the UploadServices type
type UploadServices struct {
	mock.Mock
}

// GetURLImage provides a mock function with given fields: ctxReq, url, isAttachment
func (_m *UploadServices) GetURLImage(ctxReq context.Context, url string, isAttachment string) <-chan model.ServiceResult {
	ret := _m.Called(ctxReq, url, isAttachment)

	var r0 <-chan model.ServiceResult
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan model.ServiceResult); ok {
		r0 = rf(ctxReq, url, isAttachment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.ServiceResult)
		}
	}

	return r0
}
