// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Bhinneka/user-service/src/member/v1/model"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/Bhinneka/user-service/src/member/v1/repo"
)

// DolphinLogRepository is an autogenerated mock type for the DolphinLogRepository type
type DolphinLogRepository struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0
func (_m *DolphinLogRepository) Load(_a0 int) repo.ResultRepository {
	ret := _m.Called(_a0)

	var r0 repo.ResultRepository
	if rf, ok := ret.Get(0).(func(int) repo.ResultRepository); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(repo.ResultRepository)
	}

	return r0
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *DolphinLogRepository) Save(_a0 context.Context, _a1 *model.DolphinLog) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.DolphinLog) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
