// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Bhinneka/user-service/src/member/v1/model"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/Bhinneka/user-service/src/member/v1/repo"
)

// MemberRepositoryRedis is an autogenerated mock type for the MemberRepositoryRedis type
type MemberRepositoryRedis struct {
	mock.Mock
}

// Delete provides a mock function with given fields: uid
func (_m *MemberRepositoryRedis) Delete(uid string) <-chan repo.ResultRepository {
	ret := _m.Called(uid)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(string) <-chan repo.ResultRepository); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// Load provides a mock function with given fields: uid
func (_m *MemberRepositoryRedis) Load(uid string) <-chan repo.ResultRepository {
	ret := _m.Called(uid)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(string) <-chan repo.ResultRepository); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// LoadByKey provides a mock function with given fields: ctxReq, key
func (_m *MemberRepositoryRedis) LoadByKey(ctxReq context.Context, key string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, key)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// RevokeAllAccess provides a mock function with given fields: ctxReq, key, activeKey
func (_m *MemberRepositoryRedis) RevokeAllAccess(ctxReq context.Context, key string, activeKey string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, key, activeKey)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, key, activeKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// Save provides a mock function with given fields: stc
func (_m *MemberRepositoryRedis) Save(stc *model.MemberRedis) <-chan repo.ResultRepository {
	ret := _m.Called(stc)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(*model.MemberRedis) <-chan repo.ResultRepository); ok {
		r0 = rf(stc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// SaveResendActivationAttempt provides a mock function with given fields: ctxReq, data
func (_m *MemberRepositoryRedis) SaveResendActivationAttempt(ctxReq context.Context, data *model.ResendActivationAttempt) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, data)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, *model.ResendActivationAttempt) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}
