package usecase

const (
	usrFormat                          = "USR"
	scopeSaveMemberLegacy              = "save_membership_legacy"
	scopeStatus                        = "status"
	scopeSendEmail                     = "send_email"
	msgErrorMember                     = "member with email "
	msgErrorResultMember               = "result is not member"
	msgErrorResultMerchant             = "result is not merchant"
	msgErrorResultMerchantEmployee     = "result is not merchant employee"
	msgErrorMemberID                   = "member id"
	msgErrorSaveMember                 = "failed to save member"
	msgErrorPasswordMatch              = "confirmation password did not match"
	msgErrorBirthdate                  = "date of birth"
	msgErrorStreetName                 = "street name only alphabet is allowed"
	msgErrorSendEmail                  = "failed to send email"
	msgErrorActivationMerchantEmployee = "employee status is no longer invited"
	labelMember                        = "member"
	labelPassword                      = "Password"
	textSecret                         = "secret"
	textUpdate                         = "update"
	textRegister                       = "register"
	textAdd                            = "add"
	textImport                         = "import"
	textPassword                       = "password"
	textFirstName                      = "first name"
	textLastName                       = "last name"
	textMobileNumber                   = "mobile number"
	textGender                         = "gender"
)
