// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/Bhinneka/user-service/src/service/model"

// BarracudaServices is an autogenerated mock type for the BarracudaServices type
type BarracudaServices struct {
	mock.Mock
}

// FindZipcode provides a mock function with given fields: ctxReq, data
func (_m *BarracudaServices) FindZipcode(ctxReq context.Context, data model.ZipCodeQueryParameter) <-chan model.ServiceResult {
	ret := _m.Called(ctxReq, data)

	var r0 <-chan model.ServiceResult
	if rf, ok := ret.Get(0).(func(context.Context, model.ZipCodeQueryParameter) <-chan model.ServiceResult); ok {
		r0 = rf(ctxReq, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.ServiceResult)
		}
	}

	return r0
}
