// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/Bhinneka/user-service/src/service/model"

// UploadServices is an autogenerated mock type for the UploadServices type
type UploadServices struct {
	mock.Mock
}

// GetURLImage provides a mock function with given fields: ctxReq, url
func (_m *UploadServices) GetURLImage(ctxReq context.Context, url string) <-chan model.ServiceResult {
	ret := _m.Called(ctxReq, url)

	var r0 <-chan model.ServiceResult
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan model.ServiceResult); ok {
		r0 = rf(ctxReq, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.ServiceResult)
		}
	}

	return r0
}
