// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/Bhinneka/user-service/src/auth/v1/query"
	mock "github.com/stretchr/testify/mock"
)

// AuthQuery is an autogenerated mock type for the AuthQuery type
type AuthQuery struct {
	mock.Mock
}

// GetAccountId provides a mock function with given fields: ctxReq, contactId
func (_m *AuthQuery) GetAccountId(ctxReq context.Context, contactId int) <-chan query.ResultQuery {
	ret := _m.Called(ctxReq, contactId)

	var r0 <-chan query.ResultQuery
	if rf, ok := ret.Get(0).(func(context.Context, int) <-chan query.ResultQuery); ok {
		r0 = rf(ctxReq, contactId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan query.ResultQuery)
		}
	}

	return r0
}

// UpdateLastLogin provides a mock function with given fields: uid
func (_m *AuthQuery) UpdateLastLogin(uid string) <-chan query.ResultQuery {
	ret := _m.Called(uid)

	var r0 <-chan query.ResultQuery
	if rf, ok := ret.Get(0).(func(string) <-chan query.ResultQuery); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan query.ResultQuery)
		}
	}

	return r0
}
