// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import usecase "github.com/Bhinneka/user-service/src/phone_area/v1/usecase"

// PhoneAreaUseCase is an autogenerated mock type for the PhoneAreaUseCase type
type PhoneAreaUseCase struct {
	mock.Mock
}

// GetAllPhoneArea provides a mock function with given fields: ctxReq
func (_m *PhoneAreaUseCase) GetAllPhoneArea(ctxReq context.Context) <-chan usecase.ResultUseCase {
	ret := _m.Called(ctxReq)

	var r0 <-chan usecase.ResultUseCase
	if rf, ok := ret.Get(0).(func(context.Context) <-chan usecase.ResultUseCase); ok {
		r0 = rf(ctxReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan usecase.ResultUseCase)
		}
	}

	return r0
}

// GetTotalPhoneArea provides a mock function with given fields: ctxReq
func (_m *PhoneAreaUseCase) GetTotalPhoneArea(ctxReq context.Context) <-chan usecase.ResultUseCase {
	ret := _m.Called(ctxReq)

	var r0 <-chan usecase.ResultUseCase
	if rf, ok := ret.Get(0).(func(context.Context) <-chan usecase.ResultUseCase); ok {
		r0 = rf(ctxReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan usecase.ResultUseCase)
		}
	}

	return r0
}
