// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

// GenerateSalt provides a mock function with given fields:
func (_m *PasswordHasher) GenerateSalt() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Hash provides a mock function with given fields: data
func (_m *PasswordHasher) Hash(data []byte) []byte {
	ret := _m.Called(data)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// ParseSalt provides a mock function with given fields: salt
func (_m *PasswordHasher) ParseSalt(salt string) error {
	ret := _m.Called(salt)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(salt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
