// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Bhinneka/user-service/src/session/v1/model"
	usecase "github.com/Bhinneka/user-service/src/session/v1/usecase"
	mock "github.com/stretchr/testify/mock"
)

// SessionInfoUseCase is an autogenerated mock type for the SessionInfoUseCase type
type SessionInfoUseCase struct {
	mock.Mock
}

// GetSessionInfoList provides a mock function with given fields: params
func (_m *SessionInfoUseCase) GetSessionInfoList(params *model.ParamList) <-chan usecase.ResultUseCase {
	ret := _m.Called(params)

	var r0 <-chan usecase.ResultUseCase
	if rf, ok := ret.Get(0).(func(*model.ParamList) <-chan usecase.ResultUseCase); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan usecase.ResultUseCase)
		}
	}

	return r0
}
