// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	usecase "github.com/Bhinneka/user-service/src/health/usecase"
	mock "github.com/stretchr/testify/mock"
)

// HealthUseCase is an autogenerated mock type for the HealthUseCase type
type HealthUseCase struct {
	mock.Mock
}

// Ping provides a mock function with given fields:
func (_m *HealthUseCase) Ping() <-chan usecase.ResultUseCase {
	ret := _m.Called()

	var r0 <-chan usecase.ResultUseCase
	if rf, ok := ret.Get(0).(func() <-chan usecase.ResultUseCase); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan usecase.ResultUseCase)
		}
	}

	return r0
}
