// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/Bhinneka/user-service/src/health/usecase"
	"github.com/stretchr/testify/mock"
)

// HealthUseCase is an autogenerated mock type for the HealthUseCase type
type HealthUseCase struct {
	mock.Mock
}

// Ping provides a mock function with given fields: message
func (_m *HealthUseCase) Ping() <-chan usecase.ResultUseCase {
	ret := _m.Called("Hello")

	var r0 <-chan usecase.ResultUseCase
	if rf, ok := ret.Get(0).(func(string) <-chan usecase.ResultUseCase); ok {
		r0 = rf("Hello")
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan usecase.ResultUseCase)
		}
	}

	return r0
}
