// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/Bhinneka/user-service/src/member/v1/query"
	mock "github.com/stretchr/testify/mock"
)

// MemberMFAQuery is an autogenerated mock type for the MemberMFAQuery type
type MemberMFAQuery struct {
	mock.Mock
}

// FindMFASettings provides a mock function with given fields: ctxReq, uid
func (_m *MemberMFAQuery) FindMFASettings(ctxReq context.Context, uid string) <-chan query.ResultQuery {
	ret := _m.Called(ctxReq, uid)

	var r0 <-chan query.ResultQuery
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan query.ResultQuery); ok {
		r0 = rf(ctxReq, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan query.ResultQuery)
		}
	}

	return r0
}

// FindNarwhalMFASettings provides a mock function with given fields: ctxReq, uid
func (_m *MemberMFAQuery) FindNarwhalMFASettings(ctxReq context.Context, uid string) <-chan query.ResultQuery {
	ret := _m.Called(ctxReq, uid)

	var r0 <-chan query.ResultQuery
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan query.ResultQuery); ok {
		r0 = rf(ctxReq, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan query.ResultQuery)
		}
	}

	return r0
}
