// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Bhinneka/user-service/src/merchant/v2/model"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/Bhinneka/user-service/src/merchant/v2/repo"
)

// MerchantEmployeeRepository is an autogenerated mock type for the MerchantEmployeeRepository type
type MerchantEmployeeRepository struct {
	mock.Mock
}

// ChangeStatus provides a mock function with given fields: ctxReq, params
func (_m *MerchantEmployeeRepository) ChangeStatus(ctxReq context.Context, params model.B2CMerchantEmployee) error {
	ret := _m.Called(ctxReq, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.B2CMerchantEmployee) error); ok {
		r0 = rf(ctxReq, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllMerchantEmployees provides a mock function with given fields: ctxReq, params
func (_m *MerchantEmployeeRepository) GetAllMerchantEmployees(ctxReq context.Context, params *model.QueryMerchantEmployeeParameters) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, params)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, *model.QueryMerchantEmployeeParameters) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// GetMerchantEmployees provides a mock function with given fields: ctxReq, params
func (_m *MerchantEmployeeRepository) GetMerchantEmployees(ctxReq context.Context, params *model.QueryMerchantEmployeeParameters) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, params)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, *model.QueryMerchantEmployeeParameters) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// GetTotalMerchantEmployees provides a mock function with given fields: ctxReq, params
func (_m *MerchantEmployeeRepository) GetTotalMerchantEmployees(ctxReq context.Context, params *model.QueryMerchantEmployeeParameters) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, params)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, *model.QueryMerchantEmployeeParameters) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// Save provides a mock function with given fields: _a0
func (_m *MerchantEmployeeRepository) Save(_a0 model.B2CMerchantEmployee) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.B2CMerchantEmployee) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
