// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Bhinneka/user-service/src/merchant/v2/model"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/Bhinneka/user-service/src/merchant/v2/repo"
)

// MerchantAddressRepository is an autogenerated mock type for the MerchantAddressRepository type
type MerchantAddressRepository struct {
	mock.Mock
}

// AddPhoneAddress provides a mock function with given fields: ctxReq, data
func (_m *MerchantAddressRepository) AddPhoneAddress(ctxReq context.Context, data model.PhoneData) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, data)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, model.PhoneData) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// AddUpdateAddress provides a mock function with given fields: ctxReq, data
func (_m *MerchantAddressRepository) AddUpdateAddress(ctxReq context.Context, data model.AddressData) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, data)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, model.AddressData) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// AddUpdateAddressMaps provides a mock function with given fields: ctxReq, data
func (_m *MerchantAddressRepository) AddUpdateAddressMaps(ctxReq context.Context, data model.Maps) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, data)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, model.Maps) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// CountAddress provides a mock function with given fields: ctxReq, relationID, relationName, params
func (_m *MerchantAddressRepository) CountAddress(ctxReq context.Context, relationID string, relationName string, params *model.ParameterWarehouse) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, relationID, relationName, params)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.ParameterWarehouse) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, relationID, relationName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// DeletePhoneAddress provides a mock function with given fields: ctxReq, relationID, relationName
func (_m *MerchantAddressRepository) DeletePhoneAddress(ctxReq context.Context, relationID string, relationName string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, relationID, relationName)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, relationID, relationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// DeleteWarehouseAddress provides a mock function with given fields: ctxReq, addressID
func (_m *MerchantAddressRepository) DeleteWarehouseAddress(ctxReq context.Context, addressID string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, addressID)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// FindAddressMaps provides a mock function with given fields: ctxReq, realationID, relationName
func (_m *MerchantAddressRepository) FindAddressMaps(ctxReq context.Context, realationID string, relationName string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, realationID, relationName)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, realationID, relationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// FindMerchantAddress provides a mock function with given fields: ctxReq, id
func (_m *MerchantAddressRepository) FindMerchantAddress(ctxReq context.Context, id string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, id)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// GetListAddress provides a mock function with given fields: ctxReq, params
func (_m *MerchantAddressRepository) GetListAddress(ctxReq context.Context, params *model.ParameterWarehouse) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, params)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, *model.ParameterWarehouse) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// UpdatePhoneAddress provides a mock function with given fields: ctxReq, data
func (_m *MerchantAddressRepository) UpdatePhoneAddress(ctxReq context.Context, data model.PhoneData) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, data)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, model.PhoneData) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}

// UpdatePrimaryAddressByRelationID provides a mock function with given fields: ctxReq, relationID, relationName
func (_m *MerchantAddressRepository) UpdatePrimaryAddressByRelationID(ctxReq context.Context, relationID string, relationName string) <-chan repo.ResultRepository {
	ret := _m.Called(ctxReq, relationID, relationName)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(context.Context, string, string) <-chan repo.ResultRepository); ok {
		r0 = rf(ctxReq, relationID, relationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}
