// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Bhinneka/user-service/src/session/v1/model"
	repo "github.com/Bhinneka/user-service/src/session/v1/repo"
	mock "github.com/stretchr/testify/mock"
)

// SessionInfoRepository is an autogenerated mock type for the SessionInfoRepository type
type SessionInfoRepository struct {
	mock.Mock
}

// SaveSessionInfo provides a mock function with given fields: params
func (_m *SessionInfoRepository) SaveSessionInfo(params *model.SessionInfoRequest) <-chan repo.ResultRepository {
	ret := _m.Called(params)

	var r0 <-chan repo.ResultRepository
	if rf, ok := ret.Get(0).(func(*model.SessionInfoRequest) <-chan repo.ResultRepository); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan repo.ResultRepository)
		}
	}

	return r0
}
