// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	health "github.com/Bhinneka/user-service/protogo/health"

	mock "github.com/stretchr/testify/mock"
)

// PingPongServiceClient is an autogenerated mock type for the PingPongServiceClient type
type PingPongServiceClient struct {
	mock.Mock
}

// PingPong provides a mock function with given fields: ctx, in, opts
func (_m *PingPongServiceClient) PingPong(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*health.PongResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *health.PongResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *health.PongResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.PongResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
